#!/bin/bash

# basic deps

sudo pacman -Syu;

sudo pacman -S \
	git \
	openssh \
	pass \
	firefox \
	pacutils \
	perl-json-xs \
	vifm \
	vim \
	nano \
	curl \
	gnupg \	
;

# gcm and other git-specific settings
curl -L https://aka.ms/gcm/linux-install-source.sh | sh
git-credential-manager configure
git config --global user.email "dan@dmonline.uk"
git config --global user.name dan
git config --global credential.credentialStore gpg
gpg --quick-generate-key "Daniel Morris (Happy to be here) <dan@dmonline.uk>"
pass init "Daniel Morris (Happy to be here) <dan@dmonline.uk>"

# aurutils - this is a build from AUR
# We'll test the success of the setup by
# adding aurutils using aurutils - so we
# will skip copying the package to repo

mkdir -p ~/projects/
cd ~/projects/
git clone https://aur.archlinux.org/aurutils.git#
cd ~/projects/aurutils/
makepkg -si

# This appends lines to the pacman.conf, but note
# the lines may already exist as commented out <shrug>
echo [custom] | sudo tee -a /etc/pacman.conf
echo "SigLevel = Optional TrustAll" | sudo tee -a /etc/pacman.conf
echo "file:///home/custompkgs" | sudo tee -a /etc/pacman.conf

# Create and add the repo
sudo install -d /home/custompkgs -o $USER
repo-add /home/custompkgs/custom.db.tar
sudo pacman -Syu

# Test by adding aurutils
aur sync aurutils
sudo pacman -S aurutils

# Can now drop aurutils project
rm -rf ~/projects/aurutils/
